import {
    BatchUpdateEntries,
    BatchUpdateEntryStatusByQuery,
    BrowseDirectory,
    BrowseOpenFile,
    BrowseSaveFile,
    BrowseSaveFileWithFilter,
    ClearEntryTranslationsByQuery,
    DeleteEntriesByQuery,
    GetFilterOptions,
    GetSettings,
    ListArcs,
    ListEntries,
    ListExporters,
    ListImporters,
    ListTranslators,
    ReadTextFile,
    ReparseAllArcs,
    ReparseArc,
    ReparseFailedArcs,
    RunExport,
    RunImport,
    RunMaintenance,
    RunSourceRecognition,
    RunTranslation,
    SaveSettings,
    ScanArcs,
    StopCurrentTask,
    TestASR,
    TestProxy,
    TestTranslator,
    UpdateEntry,
    WriteTextFile,
} from "../wailsjs/go/main/App";
import type {
    ArcFile,
    ASRTestResult,
    BatchDeleteResult,
    EntryList,
    EntryQuery,
    ExportRequest,
    ExportResult,
    FilterBatchStatusInput,
    FilterOptions,
    ImportRequest,
    ImportResult,
    MaintenanceResult,
    ParseResult,
    ProxyTestResult,
    ReparseAllResult,
    ReparseFailedResult,
    ScanResult,
    Settings,
    SourceRecognitionRequest,
    SourceRecognitionResult,
    TranslateRequest,
    TranslateResult,
    TranslatorTestRequest,
    TranslatorTestResult,
    UpdateEntryInput,
} from "./types";

export const api = {
    getSettings: () => GetSettings() as Promise<Settings>,
    saveSettings: (settings: Settings) => SaveSettings(settings as unknown as never) as Promise<void>,
    scanArcs: () => ScanArcs() as Promise<ScanResult>,
    listArcs: () => ListArcs() as Promise<ArcFile[]>,
    reparseArc: (arcID: number) => ReparseArc(arcID) as Promise<ParseResult>,
    reparseAllArcs: () => ReparseAllArcs() as Promise<ReparseAllResult>,
    reparseFailedArcs: () => ReparseFailedArcs() as Promise<ReparseFailedResult>,
    listEntries: (query: EntryQuery) => ListEntries(query as unknown as never) as Promise<EntryList>,
    runMaintenance: () => RunMaintenance() as Promise<MaintenanceResult>,
    getFilterOptions: () => GetFilterOptions() as Promise<FilterOptions>,
    updateEntry: (input: UpdateEntryInput) => UpdateEntry(input as unknown as never) as Promise<void>,
    batchUpdateEntries: (input: {
        ids: number[];
        translatedText: string;
        polishedText: string;
        translatorStatus: string;
    }) => BatchUpdateEntries(input as unknown as never) as Promise<{ updated: number }>,
    batchUpdateEntryStatusByQuery: (input: FilterBatchStatusInput) =>
        BatchUpdateEntryStatusByQuery(input as unknown as never) as Promise<{ updated: number }>,
    clearEntryTranslationsByQuery: (query: EntryQuery) =>
        ClearEntryTranslationsByQuery(query as unknown as never) as Promise<{ updated: number }>,
    deleteEntriesByQuery: (query: EntryQuery) =>
        DeleteEntriesByQuery(query as unknown as never) as Promise<BatchDeleteResult>,
    listImporters: () => ListImporters() as Promise<string[]>,
    runImport: (request: ImportRequest) => RunImport(request as unknown as never) as Promise<ImportResult>,
    listExporters: () => ListExporters() as Promise<string[]>,
    runExport: (request: ExportRequest) => RunExport(request as unknown as never) as Promise<ExportResult>,
    listTranslators: () => ListTranslators() as Promise<string[]>,
    runTranslation: (request: TranslateRequest) => RunTranslation(request as unknown as never) as Promise<TranslateResult>,
    runSourceRecognition: (request: SourceRecognitionRequest) =>
        RunSourceRecognition(request as unknown as never) as Promise<SourceRecognitionResult>,
    browseDirectory: (title: string, currentPath: string) => BrowseDirectory(title, currentPath) as Promise<string>,
    browseOpenFile: (title: string, currentPath: string, displayName: string, pattern: string) =>
        BrowseOpenFile(title, currentPath, displayName, pattern) as Promise<string>,
    browseSaveFile: (title: string, currentPath: string, defaultFilename: string) =>
        BrowseSaveFile(title, currentPath, defaultFilename) as Promise<string>,
    browseSaveFileWithFilter: (
        title: string,
        currentPath: string,
        defaultFilename: string,
        displayName: string,
        pattern: string,
    ) => BrowseSaveFileWithFilter(title, currentPath, defaultFilename, displayName, pattern) as Promise<string>,
    readTextFile: (path: string) => ReadTextFile(path) as Promise<string>,
    writeTextFile: (path: string, content: string) => WriteTextFile(path, content) as Promise<void>,
    stopCurrentTask: () => StopCurrentTask() as Promise<boolean>,
    testProxy: (proxy: Settings["translation"]["proxy"]) => TestProxy(proxy as unknown as never) as Promise<ProxyTestResult>,
    testASR: (settings: Settings["translation"]) => TestASR(settings as unknown as never) as Promise<ASRTestResult>,
    testTranslator: (request: TranslatorTestRequest) =>
        TestTranslator(request as unknown as never) as Promise<TranslatorTestResult>,
};
