// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function BatchUpdateEntries(arg1:model.BatchUpdateInput):Promise<model.BatchUpdateResult>;

export function BatchUpdateEntryStatusByQuery(arg1:model.FilterBatchStatusInput):Promise<model.BatchUpdateResult>;

export function BrowseDirectory(arg1:string,arg2:string):Promise<string>;

export function BrowseOpenFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BrowseSaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function BrowseSaveFileWithFilter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ClearEntryTranslationsByQuery(arg1:model.EntryQuery):Promise<model.BatchUpdateResult>;

export function DeleteEntriesByQuery(arg1:model.EntryQuery):Promise<model.BatchDeleteResult>;

export function GetFilterOptions():Promise<model.FilterOptions>;

export function GetSettings():Promise<model.Settings>;

export function ListArcs():Promise<Array<model.ArcFile>>;

export function ListEntries(arg1:model.EntryQuery):Promise<model.EntryList>;

export function ListExporters():Promise<Array<string>>;

export function ListImporters():Promise<Array<string>>;

export function ListTranslators():Promise<Array<string>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ReparseAllArcs():Promise<model.ReparseAllResult>;

export function ReparseArc(arg1:number):Promise<model.ParseResult>;

export function ReparseFailedArcs():Promise<model.ReparseFailedResult>;

export function RunExport(arg1:model.ExportRequest):Promise<model.ExportResult>;

export function RunImport(arg1:model.ImportRequest):Promise<model.ImportResult>;

export function RunMaintenance():Promise<model.MaintenanceResult>;

export function RunMaintenanceFillTranslated():Promise<model.MaintenanceResult>;

export function RunSourceRecognition(arg1:model.SourceRecognitionRequest):Promise<model.SourceRecognitionResult>;

export function RunTranslation(arg1:model.TranslateRequest):Promise<model.TranslateResult>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function ScanArcs():Promise<model.ScanResult>;

export function StopCurrentTask():Promise<boolean>;

export function TestASR(arg1:model.TranslationSettings):Promise<model.ASRTestResult>;

export function TestProxy(arg1:model.ProxyConfig):Promise<model.ProxyTestResult>;

export function TestTranslator(arg1:model.TranslatorTestRequest):Promise<model.TranslatorTestResult>;

export function UpdateEntry(arg1:model.UpdateEntryInput):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
