// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchUpdateEntries(arg1) {
  return window['go']['main']['App']['BatchUpdateEntries'](arg1);
}

export function BatchUpdateEntryStatusByQuery(arg1) {
  return window['go']['main']['App']['BatchUpdateEntryStatusByQuery'](arg1);
}

export function BrowseDirectory(arg1, arg2) {
  return window['go']['main']['App']['BrowseDirectory'](arg1, arg2);
}

export function BrowseOpenFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseOpenFile'](arg1, arg2, arg3, arg4);
}

export function BrowseSaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowseSaveFile'](arg1, arg2, arg3);
}

export function BrowseSaveFileWithFilter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BrowseSaveFileWithFilter'](arg1, arg2, arg3, arg4, arg5);
}

export function ClearEntryTranslationsByQuery(arg1) {
  return window['go']['main']['App']['ClearEntryTranslationsByQuery'](arg1);
}

export function DeleteEntriesByQuery(arg1) {
  return window['go']['main']['App']['DeleteEntriesByQuery'](arg1);
}

export function GetFilterOptions() {
  return window['go']['main']['App']['GetFilterOptions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListArcs() {
  return window['go']['main']['App']['ListArcs']();
}

export function ListEntries(arg1) {
  return window['go']['main']['App']['ListEntries'](arg1);
}

export function ListExporters() {
  return window['go']['main']['App']['ListExporters']();
}

export function ListImporters() {
  return window['go']['main']['App']['ListImporters']();
}

export function ListTranslators() {
  return window['go']['main']['App']['ListTranslators']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function ReparseAllArcs() {
  return window['go']['main']['App']['ReparseAllArcs']();
}

export function ReparseArc(arg1) {
  return window['go']['main']['App']['ReparseArc'](arg1);
}

export function ReparseFailedArcs() {
  return window['go']['main']['App']['ReparseFailedArcs']();
}

export function RunExport(arg1) {
  return window['go']['main']['App']['RunExport'](arg1);
}

export function RunImport(arg1) {
  return window['go']['main']['App']['RunImport'](arg1);
}

export function RunMaintenance() {
  return window['go']['main']['App']['RunMaintenance']();
}

export function RunMaintenanceFillTranslated() {
  return window['go']['main']['App']['RunMaintenanceFillTranslated']();
}

export function RunSourceRecognition(arg1) {
  return window['go']['main']['App']['RunSourceRecognition'](arg1);
}

export function RunTranslation(arg1) {
  return window['go']['main']['App']['RunTranslation'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanArcs() {
  return window['go']['main']['App']['ScanArcs']();
}

export function StopCurrentTask() {
  return window['go']['main']['App']['StopCurrentTask']();
}

export function TestASR(arg1) {
  return window['go']['main']['App']['TestASR'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function TestTranslator(arg1) {
  return window['go']['main']['App']['TestTranslator'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
